#!/usr/bin/env python3
"""
make_remap.py -- build the il2cpp standard->obfuscated export map for one VRChat build.

VRChat obfuscates every il2cpp_* export (Beebyte), with a fresh set of names per release, so
GetProcAddress("il2cpp_class_from_name") returns null and nothing that resolves exports by their
real name can start. This rebuilds the name map from two inputs that ARE available per build:

  * lea.json   -- the ordered obfuscated export names, as il2cpp_tables.py reads them from the run
                  of `lea reg,[rip+...]` in UnityPlayer.dll (that run is in canonical header order).
  * header.h   -- il2cpp-api-functions.h for the EXACT Unity version, from the matching git tag of
                  js6pak/libil2cpp-archive. The tag IS the Unity version, e.g.:
                    gh api repos/js6pak/libil2cpp-archive/contents/il2cpp-api-functions.h?ref=6000.0.67 \
                      -q .content | base64 -d > header.6000.0.67.h

The header declares every DO_API function in canonical order; the binary exports a subset (release
builds drop the profiler block, il2cpp_profiler_install .. il2cpp_profiler_install_thread). Lining
the two up, skipping that gap, gives standard name -> obfuscated name directly.

It is verified, not guessed: pass --check <validated.json> (names proven in-game on a prior port)
and every shared entry must agree, or the script refuses to emit. Spot-checked bodies on this build:
il2cpp_object_unbox is `lea rax,[rcx+0x10]; ret`, il2cpp_object_get_class is `mov rax,[rcx]; ret`.

Outputs (next to --out, default this dir):
  remap.<tag>.json          standard -> obfuscated, for the BepInEx Cecil remapper (cecilremap)
  il2cpp_obf_map.hpp        the same table as a C++ header for GodClient (BepInEx.Runtime)

Usage:
  python make_remap.py --header header.6000.0.67.h --lea lea.25686233.json --tag 25686233 \
      [--check remap.validated-184.25686233.json] [--hpp <path to GodClient il2cpp_obf_map.hpp>]
"""
import argparse, json, os, re, sys

PROFILER_FIRST = "il2cpp_profiler_install"
PROFILER_LAST  = "il2cpp_profiler_install_thread"


def read_header(path):
    txt = open(path, encoding="utf-8", errors="ignore").read()
    # DO_API and DO_API_NO_RETURN both declare an export; the macro's own #define matches too, so
    # keep only il2cpp_* names.
    names = [n for n in re.findall(r"DO_API(?:_NO_RETURN)?\s*\(\s*[^,]+,\s*([A-Za-z0-9_]+)\s*,", txt)
             if n.startswith("il2cpp_")]
    if not names:
        sys.exit("header: no DO_API(il2cpp_*) declarations found -- wrong file?")
    return names


def build(names, lea):
    try:
        lo = names.index(PROFILER_FIRST)
        hi = names.index(PROFILER_LAST)
    except ValueError:
        sys.exit("header: profiler block not found; gap model needs review for this Unity version")
    exported = len(names) - (hi - lo + 1)
    if exported != len(lea):
        sys.exit(f"MISMATCH: header has {len(names)} exports minus {hi-lo+1} profiler = {exported}, "
                 f"but lea has {len(lea)}. The gap is not (only) the profiler block on this build -- "
                 f"re-derive it (compare a few function bodies) before trusting any mapping.")
    out = {}
    for k, n in enumerate(names):
        if lo <= k <= hi:
            continue
        out[n] = lea[k if k < lo else k - (hi - lo + 1)]
    return out, (lo, hi)


def emit_hpp(remap, path):
    rows = sorted((k, v) for k, v in remap.items() if k != v)
    head = '''#pragma once
// GENERATED by vrchat-pack-tools/build_port_kit/make_remap.py -- do not edit by hand.
//
// VRChat obfuscates its il2cpp exports, one fresh name set per release. This maps the standard name
// to this build's obfuscated name so GetProcAddress can find each export. See make_remap.py for how
// the table is derived and cross-checked; it is pinned to ONE build and must be regenerated on every
// VRChat update. That cost is inherent to the obfuscation, not to being written in C++.

namespace GodClient::Il2CppObf {

    struct Entry { char const* standard; char const* obfuscated; };

    inline constexpr Entry kMap[] = {
'''
    body = "".join('        { "%s", "%s" },\n' % r for r in rows)
    tail = '''    };

    inline constexpr int kCount = static_cast<int>(sizeof(kMap) / sizeof(kMap[0]));

}
'''
    open(path, "w", encoding="utf-8", newline="\n").write(head + body + tail)
    return len(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--header", required=True)
    ap.add_argument("--lea", required=True)
    ap.add_argument("--tag", required=True, help="build id, e.g. 25686233")
    ap.add_argument("--check", help="a prior validated remap.json; every shared entry must match")
    ap.add_argument("--out", default=os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--hpp", help="also write the C++ header here (GodClient il2cpp_obf_map.hpp)")
    a = ap.parse_args()

    names = read_header(a.header)
    lea = json.load(open(a.lea))
    remap, gap = build(names, lea)
    print(f"header {len(names)} fns | lea {len(lea)} | profiler gap idx {gap[0]}..{gap[1]} "
          f"| mapping {len(remap)}")

    if a.check:
        prev = json.load(open(a.check))
        bad = [(n, prev[n], remap.get(n)) for n in prev if remap.get(n) != prev[n]]
        if bad:
            for n, want, got in bad[:10]:
                print(f"  DISAGREE {n}: validated={want} rebuilt={got}")
            sys.exit(f"REFUSING to emit: {len(bad)}/{len(prev)} validated entries disagree. "
                     f"The alignment is wrong -- do NOT ship this map, re-derive the gap.")
        print(f"cross-check OK: all {len(prev)} validated entries reproduced, 0 disagreements")

    out_json = os.path.join(a.out, f"remap.{a.tag}.json")
    json.dump(remap, open(out_json, "w"), indent=1, sort_keys=True)
    print("wrote", out_json)

    hpp = a.hpp or os.path.join(a.out, "il2cpp_obf_map.hpp")
    n = emit_hpp(remap, hpp)
    print(f"wrote {hpp} ({n} entries)")


if __name__ == "__main__":
    main()
